### Upload Packages

In [2]:
import pandas as pd
from Functions import *
# import warnings
# warnings.filterwarnings("ignore")

In [3]:
import plotly.graph_objects as go
import datetime
import xlrd
import re # to assign category
import numpy as np # this is for PBI
import matplotlib # this is for PBI

In [4]:
import os

### Custom Function

In [205]:
def clean_df(df):
    df.columns = df.columns.str.replace(' ', '_')
    df.columns = df.columns.str.replace(' ', '')
    df.columns = df.columns.str.lower()

    return(df)
    

def decimal_converter(value):
    try:
        return float(value.replace(',', '.'))
    except ValueError:
        return value

### l) Upload data

In [206]:
df_giugno = pd.read_excel("Raw/giugno2022.xlsx")
df_luglio = pd.read_excel("Raw/luglio2022.xlsx")
df_settembre = pd.read_excel("Raw/settembre2022.xlsx")

# clean tables and select interest columns

In [207]:
### ... Clean dataset columns 2022
## giugno 
df_giugno_clean = clean_df(df_giugno)
df_giugno_clean = df_giugno_clean.drop(df_giugno_clean.index[23:])
df_giugno_clean["data_operazione"] = pd.to_datetime(df_giugno_clean["data_operazione"]).dt.date

## luglio 
df_luglio_clean = clean_df(df_luglio)
df_luglio_clean = df_luglio_clean.drop(df_luglio_clean.index[19:])
df_luglio_clean["data_operazione"] = pd.to_datetime(df_luglio_clean["data_operazione"]).dt.date


## settembre 
df_sett_clean = clean_df(df_settembre)
df_sett_clean = df_sett_clean.drop(df_sett_clean.index[9:])
df_sett_clean["data_operazione"] = pd.to_datetime(df_sett_clean["data_operazione"]).dt.date

In [208]:
### ... Select interested columns
## giugno
df_sub_giugno = df_giugno_clean[["data_operazione", "descrizione_operazione", "importo_in_euro"]]
### ... Add Year and Month column
df_sub_giugno["year"] = pd.DatetimeIndex(df_sub_giugno["data_operazione"]).year
df_sub_giugno["month"] = pd.DatetimeIndex(df_sub_giugno["data_operazione"]).month

## luglio
df_sub_luglio = df_luglio_clean[["data_operazione", "descrizione_operazione", "importo_in_euro"]]
### ... Add Year and Month column
df_sub_luglio["year"] = pd.DatetimeIndex(df_sub_luglio["data_operazione"]).year
df_sub_luglio["month"] = pd.DatetimeIndex(df_sub_luglio["data_operazione"]).month

## settembre
df_sub_sett = df_sett_clean[["data_operazione", "descrizione_operazione", "importo_in_euro"]]
### ... Add Year and Month column
df_sub_sett["year"] = pd.DatetimeIndex(df_sub_sett["data_operazione"]).year
df_sub_sett["month"] = pd.DatetimeIndex(df_sub_sett["data_operazione"]).month

In [192]:
## There are some values with point as decimal separator, need to replace them !
df_sub_giugno["importo_in_euro"] = df_sub_giugno["importo_in_euro"].astype(str).str.replace(",", ".")

In [193]:
dataset_finance = df_sub_giugno.append(df_sub_luglio)
dataset_finance = dataset_finance.append(df_sub_sett)
dataset_finance["importo_in_euro"] = dataset_finance["importo_in_euro"].astype(float)
dataset_finance

,data_operazione,descrizione_operazione,importo_in_euro,year,month
0,2022-06-27,"PIZZA ALICE ROMA ITA EUR 10,95",10.95,2022,6
1,2022-06-26,"GROS SUPERMERCATO ROMA ITA EUR 26,29",26.29,2022,6
2,2022-06-25,"CRIDA S.R.L. - VIALE . ROMA ITA EUR 7,36",7.36,2022,6
3,2022-06-25,"LIS Pay presso NESCI ROMA ITA EUR 93,19",93.19,2022,6
4,2022-06-25,"NUNA LIE ROMA ITA EUR 29,95",29.95,2022,6
5,2022-06-22,"FARMACIE ANGELINI ROMA ITA EUR 22,50",22.50,2022,6
6,2022-06-21,"BAR RAVA' ROMA ITA EUR 4,00",4.00,2022,6
7,2022-06-19,"BARAONDA FIUMICINO ITA EUR 2,40",2.40,2022,6
8,2022-06-19,"BARAONDA FIUMICINO ITA EUR 13,00",13.00,2022,6
9,2022-06-19,"BARAONDA FIUMICINO ITA EUR 5,50",5.50,2022,6
10,2022-06-19,"EDREAMS BARCELONA ESP EUR 334,42",-334.42,2022,6
11,2022-06-17,"TUODI'MARKET ROMA MARC ROMA ITA EUR 32,47",32.47,2022,6
12,2022-06-12,"GROS SUPERMERCATO ROMA ITA EUR 53,08",53.08,2022,6
13,2022-06-12,"SATUR ROMA ITA EUR 3,89",3.89,2022,6
14,2022-06-12,"MAGGIORAZIONE SU TASSO DI CAMBIO EUR 0,00",0.10,2022,6
15,2022-06-12,"ITALKI HK LIMITED TSIMSHATSUI HKG USD 5,48",5.22,2022,6
16,2022-06-12,"PAYPAL *TELECOMITAL 35314369001 ITA EUR 10,00",10.00,2022,6
17,2022-06-10,"BAR RAVA' ROMA ITA EUR 4,00",4.00,2022,6
18,2022-06-04,"ASSITECNO ROMA ITA EUR 19,00",19.00,2022,6
19,2022-06-06,"COMMISSIONE PRELIEVO CONTANTE EUR 0,00",5.60,2022,6
20,2022-06-06,"PRELIEVO CONTANTE:ISP 0537-ROM ITA EUR 140,00",140.00,2022,6
21,2022-06-05,"AMZN Mktp IT*2G3269U84 800-279-6620 LUX EUR 25,00",25.00,2022,6
22,2022-06-01,"BAR RAVA' ROMA ITA EUR 2,00",2.00,2022,6
0,2022-07-28,"COMMISSIONE PRELIEVO CONTANTE EUR 0,00",4.00,2022,7
1,2022-07-28,"PRELIEVO CONTANTE:ISP 0537-ROM ITA EUR 100,00",100.00,2022,7
2,2022-07-27,"PAYPAL *ITALKI HK 35314369001 ITA EUR 5,66",5.66,2022,7
3,2022-07-26,"AMZN Mktp IT*9B4HI6Z25 800-279-6620 LUX EUR 15,27",15.27,2022,7
4,2022-07-17,"GROS SUPERMERCATO ROMA ITA EUR 62,78",62.78,2022,7
5,2022-07-16,"MA SUPERMERCATI ROMA ITA EUR 8,85",8.85,2022,7
6,2022-07-15,"PAYPAL *Angelog.guglie 35314369001 ITA EUR 100,00",100.00,2022,7
7,2022-07-12,"AMAZON.IT*760XE42P5 WW Luxembourg LUX EUR 134,89",134.89,2022,7
8,2022-07-12,"PAYPAL *TELECOMITAL 35314369001 ITA EUR 25,00",25.00,2022,7
9,2022-07-11,"AMZN Mktp IT*LD5NL9UG5 800-279-6620 LUX EUR 6,79",6.79,2022,7
10,2022-07-10,"FARMACIE ANGELINI ROMA ITA EUR 17,90",17.90,2022,7
11,2022-07-09,"CON.TRO BISTROT ROMA ITA EUR 60,10",60.10,2022,7
12,2022-07-08,"CRIDA S.R.L. - VIALE . ROMA ITA EUR 11,34",11.34,2022,7
13,2022-07-05,"CRIDA S.R.L. - VIALE . ROMA ITA EUR 11,30",11.30,2022,7
14,2022-07-04,"PAYPAL *mazzapaolo2019 35314369001 ITA EUR 170,00",170.00,2022,7
15,2022-07-03,"GROS SUPERMERCATO ROMA ITA EUR 55,82",55.82,2022,7
16,2022-07-02,"EURONICS ROMA ITA EUR 39,99",39.99,2022,7
17,2022-07-01,"COMMISSIONE PRELIEVO CONTANTE EUR 0,00",8.00,2022,7
18,2022-07-01,PRELIEVO CONTANTE:BNL AG. RM 6321 EU ITA EUR 2...,200.00,2022,7
0,2022-09-26,"AMZN Mktp IT*334HR9VM5 800-279-6620 LUX EUR 59,90",59.90,2022,9
1,2022-09-21,"Alice pizza ROMA ITA EUR 10,38",10.38,2022,9
2,2022-09-12,"PAYPAL *TELECOMITAL 35314369001 ITA EUR 10,00",10.00,2022,9
3,2022-09-11,"AMZN Mktp IT*VN5VY4665 800-279-6620 LUX EUR 68,06",68.06,2022,9
4,2022-09-07,"WWW.NOLEGGIARE.IT TRENTO ITA EUR 467,53",467.53,2022,9
5,2022-09-07,"WWW.MASUPERMERCATI.IT ROMA ITA EUR 68,15",68.15,2022,9
6,2022-09-07,"FARMACIE ANGELINI ROMA ITA EUR 15,30",15.30,2022,9
7,2022-09-02,"WWW.MASUPERMERCATI.IT ROMA ITA EUR 51,51",51.51,2022,9
8,2022-09-01,"FARMACIE ANGELINI ROMA ITA EUR 9,90",9.90,2022,9

In [194]:
## Remove digits from column - Lower case
## giugno
dataset_finance["descrizione_operazione"] = dataset_finance["descrizione_operazione"].str.lower()
dataset_finance["descrizione_operazione"] = dataset_finance["descrizione_operazione"].str.replace('\d+|eur|,', '')

<ipython-input-194-025d91e1311b>:4: FutureWarning: The default value of regex will change from True to False in a future version.
  dataset_finance["descrizione_operazione"] = dataset_finance["descrizione_operazione"].str.replace('\d+|eur|,', '')

### ll) Categories Column

In [195]:
# create a dictionary of mappings
mapping = {"ristorante": "pranzo o cena fuori", 
           "pizza": "pranzo o cena fuori",
           "bistrot": "pranzo o cena fuori",
           "farmacia": "farmacia",
           "farmacie": "farmacia",
           "supermercato": "spesa supermercato",
           "supermarket": "spesa supermercato",
           "supermercati": "spesa supermercato",
           "market": "spesa supermercato",
           "italki": "lezioni di inglese",
           "verbling": "lezioni di inglese",
           "amazon": "amazon",
           "amzn": "amazon",
           "edreams": "voli",
           "caffetteria": "bar",
           "ryanair": "voli",
           "bar": "bar",
           "prelievo": "prelievo",
           "prelievi": "prelievo",
           "telecomital": "ricarica telefono"}

In [196]:
def map_column(x):
    for key in mapping:
        if key.lower() in x.lower():
            return mapping[key]
    return "altro"

dataset_finance["category"] = dataset_finance["descrizione_operazione"].map(lambda x: map_column(x))

# dataset_money.loc[dataset_money["category"] == "Altro"]

In [1]:
dataset_finance[dataset_finance["category"] == "spesa supermercato"]

NameError: name 'dataset_finance' is not defined

Column Earnings - Expenditures

In [198]:
dataset_finance["type"] = dataset_finance["i2mporto_in_euro"].apply(lambda x: "earnings" if x <= 0 else "expenditures")

In [199]:
dataset_finance["importo_in_euro"] = dataset_finance["importo_in_euro"].astype(str)

Check type columns

### Write the final Dataframe obtained

In [201]:
dataset_finance.to_excel("dataset_finance.xlsx", index = False)